trigger:
- main

pool:
  name: 'Default'

steps:

- script: java -version
  displayName: 'Verify Java'

- script: mvn -version
  displayName: 'Verify Maven'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  displayName: 'Maven Build'